---
name: story_app
description: Flutter Story App
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  get_it: ^7.6.4
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  injectable: ^2.3.0
  pretty_dio_logger: ^1.3.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  google_fonts: ^6.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  dynamic_color: ^1.6.7
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  go_router: ^12.1.1
  camera: ^0.10.5+4
  image: ^4.1.3
  easy_localization: ^3.0.3
  mime: ^1.0.4
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  geolocator: ^10.1.0
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  injectable_generator: ^2.4.0
  riverpod_generator: ^2.3.2
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.4
  freezed: ^2.4.5
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
  - assets/l10n/
  - assets/google_map/
